const mongoose = require("mongoose");

// =============================================================================================
// RENTAL SCHEMA
// =============================================================================================

/**
 * Rental = Một lần thuê xe hoàn chỉnh từ lúc checkout đến return
 * 
 * Lifecycle:
 * 1. User tạo Reservation (giữ chỗ) → status = "Confirmed"
 * 2. User thanh toán VNPay → status = "pending"
 * 3. Staff cấp xe (checkout) → status = "active" + set start_actual, checkout_staff_id
 * 4. Staff nhận xe lại (checkin) → status = "Completed" + set end_actual, checkin_staff_id
 * 
 * Key relationships:
 * - renter_id: FK to User (người thuê)
 * - vehicle_id: FK to Vehicle (xe nào)
 * - reservation_id: FK to Reservation (từ reservation nào tạo ra)
 * 
 * Fields can have multiple names (for compatibility):
 * - start_time / start_actual (both accepted, start_actual is when user actually picked up)
 * - end_time / end_actual (both accepted, end_actual is when user returned)
 * - amount / estimated_amount (both work, amount is alias)
 * - estimated_cost / final_cost (estimated before trip, final after trip)
 * 
 * Created by:
 * - PaymentReturn.jsx: POST /api/rentals (after successful VNPay payment)
 */

const rentalSchema = new mongoose.Schema(
  {
    // =============================================================================================
    // IDENTIFIERS
    // =============================================================================================

    /**
     * rental_id: String (unique, indexed)
     * Format: "rt001", "rt002", etc
     * Auto-generated by POST /api/rentals controller
     * Unique to each rental record
     */
    rental_id: { type: String, unique: true, index: true },

    /**
     * reservation_id: String (optional)
     * Reference to Reservation._id that originated this rental
     * Format: "rsv001", "rsv002", etc
     * NULL if rental created without prior reservation (e.g., walk-in at station)
     * Used to link back to booking history
     */
    reservation_id: { type: String },

    /**
     * vehicle_id: String (required)
     * Reference to Vehicle.vehicle_id (e.g., "v001")
     * Immutable once rental created
     * Used to fetch vehicle details, pricing, specifications
     */
    vehicle_id: { type: String, required: true },

    /**
     * renter_id: String (required)
     * Reference to User.user_id or User.renter_id
     * Set automatically from JWT token when creating rental
     * Used to identify who rented the vehicle
     */
    renter_id: { type: String, required: true },

    // =============================================================================================
    // TIME FIELDS
    // =============================================================================================

    /**
     * start_time: Date (optional)
     * Originally planned/requested start time from Reservation
     * May differ from start_actual if checkout delayed
     * Format: ISO 8601 datetime
     */
    start_time: { type: Date },

    /**
     * end_time: Date (optional)
     * Originally planned/requested end time from Reservation
     * May differ from end_actual if return delayed
     * Format: ISO 8601 datetime
     */
    end_time: { type: Date },

    /**
     * start_actual: Date (optional)
     * Actual time when staff handed vehicle to renter (during checkout)
     * Set by staff when pressing "Confirm Checkout" button
     * This is THE actual rental start time for billing
     * NULL until checkout completed
     */
    start_actual: { type: Date },

    /**
     * end_actual: Date (optional)
     * Actual time when renter returned vehicle (during checkin)
     * Set by staff when pressing "Confirm Checkin" button
     * This is THE actual rental end time for billing
     * NULL until checkin completed
     */
    end_actual: { type: Date },

    // =============================================================================================
    // STATUS & WORKFLOW
    // =============================================================================================

    /**
     * status: Enum String
     * Tracks rental lifecycle state
     * 
     * Workflow:
     * - "pending": Rental created after VNPay payment, awaiting staff checkout
     * - "active" / "Ongoing": Staff has handed vehicle to renter (checkout done)
     * - "Completed": Renter returned vehicle, rental finished (checkin done)
     * - "Cancelled": Rental was cancelled (refund issued if applicable)
     * 
     * Note: Mixed naming due to legacy code (pending/active vs Pending/Ongoing)
     * Both should be normalized to lowercase in migration
     */
    status: {
      type: String,
      enum: ["pending", "active", "Pending", "Ongoing", "Completed", "Cancelled"],
      default: "active",
    },

    // =============================================================================================
    // VEHICLE CONDITION TRACKING
    // =============================================================================================

    /**
     * start_battery: Number (optional, in %)
     * Battery % when vehicle given to renter at checkout
     * Example: 85 (means 85%)
     * Captured during checkout handover process
     * Used to calculate battery degradation during trip
     */
    start_battery: { type: Number },

    /**
     * end_battery: Number (optional, in %)
     * Battery % when vehicle returned by renter at checkin
     * Example: 42 (means 42%)
     * Captured during checkin return process
     * Used to calculate usage and billing adjustments
     */
    end_battery: { type: Number },

    /**
     * start_odo: Number (optional, in km)
     * Odometer reading when vehicle given to renter at checkout
     * Example: 5000 (means 5000 km traveled before rental)
     * Captured during checkout handover process
     */
    start_odo: { type: Number },

    /**
     * end_odo: Number (optional, in km)
     * Odometer reading when vehicle returned by renter at checkin
     * Example: 5150 (means 5150 km traveled before return)
     * Captured during checkin return process
     * Used to calculate distance traveled: end_odo - start_odo
     */
    end_odo: { type: Number },

    // =============================================================================================
    // STAFF ASSIGNMENTS
    // =============================================================================================

    /**
     * checkout_staff_id: String (optional)
     * User.user_id of staff member who did checkout (handed vehicle to renter)
     * NULL if not checked out yet or if self-checkout (automated kiosk)
     * Used for audit trail and accountability
     */
    checkout_staff_id: { type: String },

    /**
     * checkin_staff_id: String (optional)
     * User.user_id of staff member who did checkin (received vehicle back)
     * NULL if not checked in yet
     * Used for audit trail and accountability
     */
    checkin_staff_id: { type: String },

    // =============================================================================================
    // BILLING FIELDS
    // =============================================================================================

    /**
     * estimated_cost: String (optional)
     * Originally estimated total cost with currency
     * Format: "150000 VND"
     * Calculated from Reservation.estimated_amount using quote
     * May differ from final_cost if rental duration exceeded estimate
     */
    estimated_cost: { type: String },

    /**
     * estimated_amount: Number (optional)
     * Numeric version of estimated_cost (without currency suffix)
     * Example: 150000 (in VND)
     * Used for calculations and comparisons
     * Copied from Reservation.estimated_amount
     */
    estimated_amount: { type: Number },

    /**
     * final_cost: String (optional)
     * Actual total cost after checkin completion
     * Format: "145000 VND"
     * Calculated based on actual rental duration and any fees/penalties
     * Differs from estimated_cost if:
     * - Trip ended earlier (discount) or later (penalty)
     * - Damage fees applied
     * - Extended rental charges added
     * NULL until checkin completed
     */
    final_cost: { type: String },

    /**
     * amount: Number (optional)
     * Alias for estimated_amount
     * Both point to same value conceptually
     * Use estimated_amount (more explicit name) in new code
     * Kept for backward compatibility
     */
    amount: { type: Number },
  },
  { timestamps: true } // Adds createdAt, updatedAt automatically
);

// =============================================================================================
// TIMESTAMPS
// =============================================================================================

/**
 * createdAt: Date (auto)
 * When rental record was created in database
 * Example: 2024-12-19T15:30:00.123Z
 * Set by Mongoose when document first saved
 * Usually matches when POST /rentals was called
 * 
 * updatedAt: Date (auto)
 * When rental record was last modified
 * Updated automatically on each save() call
 * Used to track status changes (pending → active → Completed)
 */

module.exports = mongoose.model("Rental", rentalSchema);
