const mongoose = require('mongoose');

// =============================================================================================
// RESERVATION SCHEMA
// =============================================================================================

/**
 * Reservation = Giữ chỗ / booking tạm thời trước khi thanh toán
 * 
 * Lifecycle:
 * 1. User chọn xe + thời gian → POST /api/reservations → status = "Confirmed" (ngay)
 * 2. User thanh toán VNPay → backend cập nhật status = "Confirmed" (redundant)
 * 3. User nhân rental từ reservation → Rental created (có link qua reservation_id)
 * 4. Rental completed → Reservation status vẫn "Confirmed" (không cần update)
 * 
 * Difference từ Rental:
 * - Reservation: Tạm thời, giữ chỗ, chưa thanh toán (thường)
 * - Rental: Chính thức, sau khi thanh toán, có tracking checkout/checkin
 * 
 * Key relationships:
 * - renter_id: FK to User (người book)
 * - vehicle_id: FK to Vehicle (xe nào)
 */

const reservationSchema = new mongoose.Schema(
  {
    // =============================================================================================
    // IDENTIFIERS
    // =============================================================================================

    /**
     * reservation_id: String (unique, indexed)
     * Primary identifier for this reservation
     * Format: "rsv001", "rsv002", etc
     * Auto-generated by POST /api/reservations controller
     * Unique across all reservations
     * Used as reference in Payment provider (VNPay - stored as vnp_TxnRef)
     * Used to link Rental.reservation_id back to this booking
     */
    reservation_id: { type: String, unique: true, index: true },

    /**
     * renter_id: String (required)
     * Reference to User._id or User.user_id who made this booking
     * Extracted from JWT token during POST /api/reservations
     * Used to filter reservations by user (GET /api/reservations/me)
     * Cannot be changed after creation
     */
    renter_id: { type: String, required: true },

    /**
     * vehicle_id: String (required)
     * Reference to Vehicle.vehicle_id (e.g., "v001", "v002")
     * Specifies which vehicle is being reserved
     * Cannot be changed after creation (immutable)
     * Used to display vehicle details, pricing
     */
    vehicle_id: { type: String, required: true },

    // =============================================================================================
    // TIME RANGE
    // =============================================================================================

    /**
     * start_time: Date (required)
     * When user wants to start renting the vehicle
     * Format: ISO 8601 datetime (e.g., "2024-12-20T08:00:00Z")
     * Extracted from VehicleDetail.jsx booking form
     * Used to calculate duration for billing quote
     * Immutable after creation
     */
    start_time: { type: Date, required: true },

    /**
     * end_time: Date (required)
     * When user wants to return the vehicle
     * Format: ISO 8601 datetime (e.g., "2024-12-20T10:00:00Z")
     * Extracted from VehicleDetail.jsx booking form
     * Used to calculate duration for billing quote
     * Immutable after creation
     * 
     * Special logic: If end_time <= start_time, add 24 hours
     * Example: start 20:00, end 08:00 → actually 08:00 next day
     */
    end_time: { type: Date, required: true },

    // =============================================================================================
    // STATUS & WORKFLOW
    // =============================================================================================

    /**
     * status: Enum String
     * Tracks reservation lifecycle
     * 
     * Enum values:
     * - 'Pending': Initial state (rarely used, usually jumps to Confirmed)
     * - 'Confirmed': Valid booking, ready for payment/rental
     * - 'Cancelled': User cancelled or refund processed
     * - 'Completed': Associated rental was completed (optional tracking)
     * 
     * Default: 'Pending'
     * 
     * Typical flow:
     * 1. POST /api/reservations → status = "Confirmed" (bypasses Pending)
     * 2. User pays VNPay → IPN might update to "Confirmed" (idempotent)
     * 3. Staff process rental → stays "Confirmed"
     * 4. (Optional) After rental complete → update to "Completed"
     */
    status: {
      type: String,
      enum: ['Pending', 'Confirmed', 'Cancelled', 'Completed'],
      default: 'Pending'
    },

    // =============================================================================================
    // FINANCIAL & DEPOSIT
    // =============================================================================================

    /**
     * hold_deposit: String (optional)
     * Security deposit amount held during reservation
     * Format: "500000 VND" (includes amount + currency)
     * Typical amount: 500,000 VND (~$20 USD equivalent)
     * Set during POST /api/reservations creation
     * Locked for duration of reservation
     * Returned to customer upon successful rental completion
     * 
     * TODO: Consider splitting into:
     * - hold_deposit_amount: Number (e.g., 500000)
     * - hold_deposit_currency: String (e.g., "VND")
     * For easier calculations and internationalization
     */
    hold_deposit: { type: String },

    /**
     * estimated_amount: Number (optional)
     * Total rental cost calculated at booking time
     * Format: Pure number in VND (e.g., 100000)
     * Calculated by:
     * 1. Fetch vehicle → get price_per_hour
     * 2. Calculate hours: (end_time - start_time) / 3600000
     * 3. Amount = hours * price_per_hour (rounded up)
     * 
     * Used for:
     * - Display on Checkout page
     * - VNPay payment amount (converted to vnp_Amount = amount*100)
     * - Populate Rental.estimated_amount when creating rental
     * - Compare with final_cost for dispute resolution
     * 
     * Note: This is estimate, actual may differ if:
     * - Rental started late or ended early
     * - Damage fees applied
     * - Promotions or discounts applied
     */
    estimated_amount: { type: Number },

    /**
     * currency: String (optional)
     * Currency of amounts in this reservation
     * Default: 'VND' (Vietnamese Dong)
     * Used for display (e.g., "100,000 VND")
     * Kept separate in case future multi-currency support
     */
    currency: { type: String, default: 'VND' },

    // =============================================================================================
    // METADATA
    // =============================================================================================

    /**
     * created_by_staff: String (optional, default: null)
     * User.user_id of staff member who created this reservation
     * 
     * Workflow:
     * - If renter created themselves: null (they used website/app)
     * - If staff created on behalf: set to staff.user_id (walk-in at station)
     * 
     * Use cases:
     * - Track if booking was online vs in-person
     * - Accountability for staff walk-in bookings
     * - Report generation (online vs counter sales)
     */
    created_by_staff: { type: String, default: null },
  },
  { timestamps: true } // Adds createdAt, updatedAt
);

// =============================================================================================
// TIMESTAMPS (Auto-managed by Mongoose)
// =============================================================================================

/**
 * createdAt: Date (auto)
 * When this reservation was created in database
 * Example: 2024-12-19T15:30:00.123Z
 * Set automatically by MongoDB when document saved
 * Usually matches POST /api/reservations request time
 * Used for audit trail
 * 
 * updatedAt: Date (auto)
 * When this reservation was last modified
 * Updated on any .save() call
 * Used to track status changes (Pending → Confirmed, Confirmed → Cancelled, etc)
 * Updated by VNPay IPN endpoint when confirming payment
 */

module.exports = mongoose.model('Reservation', reservationSchema);
